---
- hosts: Database-Master
  vars:
    rep_pw: bingo
  vars_files:
    - vars/master.yml
  roles:
    - role: ansible-role-mysql
      become: yes
- hosts: Database-Slave
  vars:
    rep_pw: bingo
  vars_files:
    - vars/slave.yml
  roles:
    - role: ansible-role-mysql
      become: yes
